### ISSUE TITLE
Results are different for two ways of specifying same moments

### ISSUE THREAD

**Issue by johnnybonney** [jkcshea/ivmte#151]
@cblandhol pointed out some behavior to me that we find concerning. We could be mistaken, however, so to illustrate, I will walk through an example.

```
# setup
library(data.table)
library(ivmte)

set.seed(1001)
N <- 2000

dt <- data.table(
  id = 1:N,
  u = runif(N),
  z = sample(0:1, N, replace = T),
  epsilon = rnorm(N, sd = .1)
)

dt[, p := (z == 0)*0.29 + (z == 1)*0.78]
dt[, d := as.integer(u <= p)]
dt[, y0 := 0.9 - 1.1*u + 0.3*u^2]
dt[, y1 := 0.35 - 0.3*u - 0.05*u^2]
dt[, y := y1*d + y0*(1 - d) + epsilon]

dt[, dz.grp := .GRP, by = .(d, z)] # for nonparametric regression
```

Consider the following two specifications:
```
y ~ d + z + d:z  # standard linear regression
y ~ factor(dz.grp)  # "nonparametric" regression
```
They each yield four moments that (from our understanding) contain the same information. The second specification should directly yield the four moments proposed in the BMW 2017 paper: E[Y|D=1,Z=1], E[Y|D=0,Z=1] , E[Y|D=1,Z=0] , E[Y|D=0,Z=0] (and the first should indirectly yield that information). Either should give us enough information to point identify a linear MTE.

However, specifying the `ivlike` argument to be these two different specifications gives significantly different results:
```
args_test <- list(
  data = dt,
  propensity = d ~ z,
  m0 = ~u,
  m1 = ~u,
  target = "ate",
  lpsolver = "gurobi"
)

# first, specify a usual linear regression
args_test$ivlike <- y ~ d + z + d:z
res.test <- do.call(ivmte, args_test)
```
```
...
Minimum criterion: 0.008603596
...
Bounds on the target parameter: [-0.2356282, -0.2356282]
```
With the usual regression specification, we are able to point identify the MTE.
```
# now, use nonparametric regression
args_test$ivlike <- y ~ factor(dz.grp)
res.test <- do.call(ivmte, args_test)
```
```
...
Minimum criterion: 0.08039548
...
Bounds on the target parameter: [-0.3971575, -0.2319273]
```
With the "nonparametric" regression specification, our fit gets 10x worse, and our bounds are much wider.

It is definitely possible that there is some gap in our understanding, but up until now, we thought that both specifications would give identical results. If we were misguided in this assumption (and this `ivmte` behavior is not unusual), it would be useful for us to understand why.

**Comment by a-torgovitsky** [comment]
Did you try implementing the regression in the BMW paper?
Does it give `-.236`?
If so, my guess is there's something weird going on with the components being selected from `factor(dz.grp)` in the second specification, but Josh can provide a more intelligent view here.
Does it say how many moments are being calculated when you turn `noisy = TRUE`?

**Comment by johnnybonney** [comment]
> Did you try implementing the regression in the BMW paper?

I just now implemented the regression from Table 4 in the paper (where they compare results from the IV specification to the linear MTE model). I had to make two adjustments:
1. Since the target parameter in the comparison is the LATE, I switched to the LATE from the ATE.
2. I removed the default `m0` and `m1` upper/lower bounds (otherwise, moments are not precisely matched and the regression results don't match the extrapolation results)

```
args_test <- list(
  data = dt,
  propensity = d ~ z,
  m0 = ~u,
  m1 = ~u,
  target = "late",
  late.to = list("z" = 1),
  late.from = list("z" = 0),
  lpsolver = "gurobi",
  m0.lb = -Inf, m0.ub = Inf,
  m1.lb = -Inf, m1.ub = Inf
)

args_test$ivlike <- y ~ d + z + d:z # linear regression
mte.res <- do.call(ivmte, args_test)
> Bounds on the target parameter: [-0.2378015, -0.2378015]

AER::ivreg(y ~ d | z, data = dt) # normal IV
> Coefficients:
> (Intercept)            d  
>      0.3903      -0.2378
```
They indeed match. Now that I have removed the MTR upper/lower bounds, though, the results with the `y ~ factor(dz.grp)` change -- in fact, I am no longer able to obtain any bounds at all. The LP problem is always unbounded.

> Does it say how many moments are being calculated when you turn `noisy = TRUE`?

Yes -- in both cases, it says four moments are being calculated. Oddly, though, when I investigate the original case with `factor(dz.grp)` (without removing the default upper/lower bounds), I get
```
qr(res.test$lpresult$model$A[2:5, 9:12])$rank # moment conditions in constraint matrix
> [1] 2
```
-- indicating that only two of the moments `ivmte` pulls from `factor(dz.grp)` are independent. This seems odd to me. (For comparison, all four of the moments `ivmte` pulls from `y ~ d + z + d:z` are independent.)

**Comment by jkcshea** [comment]
> indicating that only two of the moments ivmte pulls from factor(dz.grp) are independent. 

If I've done the math correctly, this is indeed true and should be the case.

-----------------

I think the issue stems back to the OLS weights:

![image](https://user-images.githubusercontent.com/8278206/68910601-0607b780-0718-11ea-8c5b-8c7e703c9bf9.png)

The $\omega_s$ weights for `D = 0` and `D = 1` in an OLS specification are supposed to differ in two ways:

1. The indicator function accounting for selection
1. The `s(d, x, z)` function that weights the treated/control observations.

But the IV-like specification `y ~ factor(dz.grp)` doesn't depend on `D`.
Hence, the `s(d, x, z)` function will be the same for `d = 0` and `d = 1`, and the treated and control observations are not weighted properly.

If the above makes sense, then I think what is happening is that the `ivmte` function simply isn't able to extract all the information from IV-like specifications that
1. Can be estimated using OLS
2. Do not include `D`

**Comment by jkcshea** [comment]
Also, if an OLS specification is stated as an IV specification, you run into the same problem.
e.g.
```
## Try redundant TSLS
devtools::load_all("../ivmte")
args_test$ivlike <- y ~ d + z + d:z | d + z + d:z
args_test$point <- FALSE
res.test3 <- do.call(ivmte, args_test)
```
The bounds for this are ` [-0.3575267, -0.3239503]`.
Point identification is not possible either.

I should mention that the function already checks whether IV specifications are unnecessary, i.e. it checks if the excluded instruments indeed excluded from the second stage; if not, an error is spit out.

**Comment by johnnybonney** [comment]
> But the IV-like specification `y ~ factor(dz.grp)` doesn't depend on D.

Hmm. I see what you are saying. I mean, `dz.grp` *does* depend on `d` (by construction), but that dependence is not explicit in the `ivlike` argument...

So, take the following example (using the same initial setup):
```
dt[, `:=` (d1z1 = as.integer(d == 1 & z == 1),
           d1z0 = as.integer(d == 1 & z == 0),
           d0z1 = as.integer(d == 0 & z == 1),
           d0z0 = as.integer(d == 0 & z == 0))]

args_test <- list(
  data = dt,
  propensity = d ~ z,
  m0 = ~u,
  m1 = ~u,
  target = "ate",
  lpsolver = "gurobi",
  m1.lb = -Inf, m1.ub = Inf,
  m0.lb = -Inf, m0.ub = Inf
)

# specification 1: standard linear regression
args_test$ivlike <- y ~ d + z + d:z
res <- do.call(ivmte, args_test)
> Bounds on the target parameter: [-0.2534239, -0.2534239]

# specification 2: nonparametric (direct)
args_test$ivlike <- y ~ 0 + d:z + d:I(1-z) + I(1-d):z + I(1-d):I(1-z)
res <- do.call(ivmte, args_test)
> Bounds on the target parameter: [-0.2534239, -0.2534239]

# specification 3: nonparametric (indirect) (equivalent to using factor(dz.grp))
args_test$ivlike <- y ~ 0 + d1z1 + d1z0 + d0z1 + d0z0
res <- do.call(ivmte, args_test)
# function only pulls out two independent moments, so LP problem always unbounded
```
We see that specification 2 works as expected (and returns same result as specification 1).

If I am understanding you correctly, while the specification 2 and specification 3 regressions are *exactly* equivalent, `ivmte` uses them differently because specification 3 does not include `d` directly. Is that right? That seems unattractive (though perhaps necessary for computational purposes).

If it is difficult (impossible?) for `ivmte` to accommodate IV-like moments that do not explicitly include `d`, are you worried that this behavior will trip up users?

**Comment by jkcshea** [comment]
> Hmm. I see what you are saying. I mean, dz.grp does depend on d (by construction), but that dependence is not explicit in the ivlike argument...

Sorry, that is what I meant to say.
The `ivmte` function needs _explicit_ inclusion of `d` in the IV-like specifications.

The reason boils down to how I generate the `s(d, x, z)` weights.
To generate `s(0, x, z)`, I set all `d = 0` in the data, then use R's built in functions to construct the design matrix _based on the IV-like formula_.
And to generate `s(1, x, z)`, I set all `d = 1`, and reconstruct the design matrix.
So if the IV-like formula does not explicitly include `d`, then setting all `d = 0` or `d = 1` isn't going to matter when R constructs the design matrices---R doesn't think there is a `d` involved at all.
Consequently `s(0, x, z)` will be the same as `s(1, x, z)`.

> If it is difficult (impossible?) for ivmte to accommodate IV-like moments that do not explicitly include d, are you worried that this behavior will trip up users?

Maybe it's possible, but I'm not sure how at the moment.
For instance, suppose you passed `y ~ factor(dz.grp)` as the IV-like specification, without any further information.
I'm not sure how I (or R) would be able to determine (in an efficient manner) that `factor(dz.grp)` was constructed using both `d` and `z`.

**Comment by a-torgovitsky** [comment]
@jkcshea  this makes a lot of sense, since you need to somehow be able to find the "d" column, so I am not sure there is a way around this.

But, in @johnnybonney 's third example above, this problem means that there are really just 2 non-redundant moments, right? Or are there actually 4 moments, just that they aren't weighting d = 0 and d = 1 correctly?

Also, this example is a bit concerning to me:
```
## Try redundant TSLS
devtools::load_all("../ivmte")
args_test$ivlike <- y ~ d + z + d:z | d + z + d:z
args_test$point <- FALSE
res.test3 <- do.call(ivmte, args_test)
```
Why exactly doesn't that work? Are you using two different weighting formulas for OLS and TSLS?
The TSLS weighting formula should be a strict generalization...so I'm not sure why this would be necessary.

**Comment by jkcshea** [comment]
Just to clarify, I believe this problem is specific to OLS specifications.
For actual TSLS specifications, the `s(d, x, z)` functions do not vary with `d`.
This is why, when I posted this second example involving a "redundant" TSLS specificaiton:
```
args_test$ivlike <- y ~ d + z + d:z | d + z + d:z
```
we also fail to get point identification and get redundant moments: the `s(1, x, z)` and `s(0, x, z)` functions will---and should---be the same.

**Comment by jkcshea** [comment]
> Why exactly doesn't that work? Are you using two different weighting formulas for OLS and TSLS?
The TSLS weighting formula should be a strict generalization...so I'm not sure why this would be necessary.

Hm, but I thought the TSLS weights aren't supposed to include `d`.

![image](https://user-images.githubusercontent.com/8278206/68956000-c9c26e80-078c-11ea-8dcc-55ea41767b73.png)

Or rather, all the `d` has been integrated out.

**Comment by a-torgovitsky** [comment]
That's just because the notation in the paper is less general than what we are doing here.
\tilde{Z} in the paper is defined as [1, Z, X],
This does not encompass all of the types of things we can do in the module.
(For example, we can include terms like Z*X too.)

If we allow \tilde{Z} to contain D components (unlike in the paper notation), then the TSLS weights will also be asymmetric for d = 0 and d = 1.

Presumably, you have a way of "parsing" the d components for OLS specifications, right?
Because for those the module also handles something that is more general than in the paper, e.g.
```r
y ~ d + z + d:z
```
Look at Table II of the paper, but imagine that \tilde{X} is more generally specified, so that it can have interactions between D and X as well.
Then in this specification
s(0, z) is going to have "\tilde{x}" vectors like [1, 0, z, 0]
while
s(1,z) is going to have "\tilde{x}" vectors like [1, 1, z, z]

So, how did you figure that out for OLS? Is it not also possible to do it for TSLS?

**Comment by jkcshea** [comment]
Ah, right, I wasn't thinking very generally then.

> Presumably, you have a way of "parsing" the d components for OLS specifications, right?

Yes, we determine the `d` variable from either the `treat` option, or from the response variable in the propensity model.
This then allows me to find the `d` components in the IV-like specifications.

> So, how did you figure that out for OLS? Is it not also possible to do it for TSLS?

It should indeed be very straightforward to do this for TSLS.
It would be the same procedure I described above with OLS.
I can probably collapse the code for OLS and TSLS weights into one chunk then.
Sorry for not having realized this earlier, despite the countless examples.

**Comment by a-torgovitsky** [comment]
Hmm, ok but then my guess is you will be able to find things like this:
```r
## Try redundant TSLS
devtools::load_all("../ivmte")
args_test$ivlike <- y ~ d + z + d:z | d + z + d:z
args_test$point <- FALSE
res.test3 <- do.call(ivmte, args_test)
```

But that @johnnybonney 's example
```r
# specification 3: nonparametric (indirect) (equivalent to using factor(dz.grp))
args_test$ivlike <- y ~ 0 + d1z1 + d1z0 + d0z1 + d0z0
res <- do.call(ivmte, args_test)
# function only pulls out two independent moments, so LP problem always unbounded
```
is still going to be a problem?

Is that right? My understanding is that in the second example "finding `d`" is hard because it's only entering through derived variables?
Is that correct?

**Comment by jkcshea** [comment]
Right, so I will adjust the code to be able to handle this:
```
args_test$ivlike <- y ~ d + z + d:z | d + z + d:z
```

But I still don't see a way to resolve @johnnybonney's example, where `d` only enters through derived variables.

**Comment by a-torgovitsky** [comment]
Yeah I don't see how either.

We certainly don't want to force the user to include `d`.
But without knowing the functional form of a variable like `d1z1`, I'm just not sure how this could be inferred.

However, in this example
```r
# specification 3: nonparametric (indirect) (equivalent to using factor(dz.grp))
args_test$ivlike <- y ~ 0 + d1z1 + d1z0 + d0z1 + d0z0
res <- do.call(ivmte, args_test)
# function only pulls out two independent moments, so LP problem always unbounded
```
Am I right that there are really only 2 distinct moments conditions, not 4, since we treat it symmetrically for `d = 0` and `d = 1`?

**Comment by jkcshea** [comment]
> Am I right that there are really only 2 distinct moments conditions, not 4, since we treat it symmetrically for d = 0 and d = 1?

Yep, that's right.

But just to be clear: the `s(d, x, z)` functions are being treated symmetrically for `d = 0` and `d = 1`.
But the omega_s weights still differs across `d = 0` and `d = 1`, because of the additional indicator function defining the bounds of integration.

**Comment by a-torgovitsky** [comment]
Ah ok, yes that's right regarding the indicator functions.

So `ivmte` does not drop redundant IV--like specifications?
I had thought that you had coded this in at some point.

**Comment by jkcshea** [comment]
Hm, [here](https://github.com/jkcshea/ivmte/issues/138#issuecomment-548628678) in #138, we discussed dropping redundant IV-like _components_ under point identification.
The motivation was so that our weight matrices would be invertible.
I didn't think about bringing it over to partial identificatoin, though.
Shouldn't be hard to do so, albeit I don't think there is much to gain from it (i.e. we would need to carry out the same calculations to determine if the moments are redundant, and the LP solvers seem very quick to drop redundant restrictions).

But I haven't considered dropping redundant IV-like _specifications_.
Are you referring to `y ~ d + z + d:z | d + z + d:z`?
If so, I shouldn't have called it a "redundant" specification.
Rather, I meant that it is written as though it requires TSLS, but it does not.
By the way, that issue has now been resolved, i.e. `y ~ d + z + d:z` and `y ~ d + z + d:z | d + z + d:z` yield the same estimates.

But let me know if you want to drop redundant restrictions under partial identification.
Perhaps the user will enjoy messages like (taken from #138):
```R
Warning message:
The following components have been dropped due to collinearity: 
 IV-like Spec.     Component
 ----------------------------------------------
 2                 factor(z)2 
 3                 (Intercept) 
 3                 d 
 4                 (Intercept) 
 4                 d 
 4                 z 
```

**Comment by jkcshea** [comment]
If we do decide to drop redundant moments, though. the code will essentially drop entire specifications if all the moments are redundant.

**Comment by a-torgovitsky** [comment]
Sorry, I wasn't clear on that.
I was talking about this example:
```r
# specification 3: nonparametric (indirect) (equivalent to using factor(dz.grp))
args_test$ivlike <- y ~ 0 + d1z1 + d1z0 + d0z1 + d0z0
res <- do.call(ivmte, args_test)
# function only pulls out two independent moments, so LP problem always unbounded
```

I guess what's disturbing about this example is that the user doesn't have any indication that they aren't getting what they think they are getting.
I was thinking that one way around that would be to remove redundant moments, so that they might notice that they only have 2 here, instead of 4.

But I think getting into the business of dropping moments seems a bit dangerous.

So perhaps we just resign ourselves to specifications like these being beyond what we can handle?

**Comment by jkcshea** [comment]
Maybe instead of dropping moments, we can just check the rank of the constraint matrix pertaining to the equality constraints?
Then we we report back something like, `2/5 linearly independent moment conditions`.

**Comment by johnnybonney** [comment]
Whatever you end up doing, I think it is important to make it clear to the user that if the IV-like specifications are functions of `d`, those functions need to be direct. Perhaps even going so far as to spit out a warning if `d` is not a component of each specification or something.

It is worrisome to me that I have been using the package for so long and am just now finding this out. I would not be surprised if (absent adequate warning) other users make the same error.

**Comment by a-torgovitsky** [comment]
I like the idea of reporting the number of linearly independent estimands.
Perhaps if it is less than the total number, then we spit out a warning about how anything involving "d" needs to be included explicitly?

I am concerned that warning a user if they do this:
```r
y ~ factor(z)
```
is going to lead to a lot of false flags.

**Comment by jkcshea** [comment]
How does this look?

I've added in a counter for independent moment conditions; as well as the warning message that pops out only when the number of independent moment conditions is less than the number of IV-like components, **and** there include IV-like specifications without the treatment variable.


```R
> args_test$ivlike <- c(y ~ factor(z) + d:factor(z),
+                       y ~ factor(z))
> test_res <- do.call(ivmte, args_test)

LP solver: Gurobi ('gurobi')

Obtaining propensity scores...

Generating target moments...
    Integrating terms for control group...
    Integrating terms for treated group...

Generating IV-like moments...
    Moment 1...
    Moment 2...
    Moment 3...
    Moment 4...
    Moment 5...
    Moment 6...
    Moment 7...
    Moment 8...
    Moment 9...
    Moment 10...
    Moment 11...
    Moment 12...
    Independent moments: 4 

Performing audit procedure...
    Generating audit grid...
    Generating initial constraint grid...

    Audit count: 1
    Minimum criterion: 0.1158851
    Obtaining bounds...
    Violations: 0
    Audit finished.

Bounds on the target parameter: [-0.2744784, -0.2744784]

Warning message:
The following IV-like specifications do not include the treatment variable: 2. 
This may result in fewer independent moment conditions than expected. 
```

**Comment by a-torgovitsky** [comment]
I think that's great!
Does the warning only get triggered for OLS specifications?

**Comment by jkcshea** [comment]
It also gets triggered for TSLS specifications.

So there are two conditions that must be met for this warning to be thrown:
1. Number of independent moment conditions is less than the total number of components
1. Not all IV-like specifications, regardless of OLS or TSLS type, include the treatment variable.

Is this how it should be?

**Comment by a-torgovitsky** [comment]
Makes sense to me, let's go with that
