### ISSUE TITLE
Factor variables in IV-like specifications generating error message

### ISSUE THREAD

**Issue by johnnybonney** [jkcshea/ivmte#152]
In certain specifications, it seems like `ivmte` has some internal inconsistencies with the IV-like moment and the components list, and the function breaks. (This seems to only happen when the only IV-like moment included is a factor variable is interacted with another variable.)

**[Edit: This also occurs when `ivlike = y ~ d + d:factor(z)`. So I am wrong to say it *only* happens when the only IV-like moment is the interaction.**]

```
library(data.table)
library(ivmte)

set.seed(1001)
N <- 2000

dt <- data.table(
  id = 1:N,
  u = runif(N),
  z = sample(1:4, N, replace = T),
  epsilon = rnorm(N, sd = .1)
)

dt[, p := (z == 1)*0.12 + (z == 2)*0.29 + (z == 3)*0.48 + (z == 4)*0.78]
dt[, d := as.integer(u <= p)]
dt[, y0 := 0.9 - 1.1*u + 0.3*u^2]
dt[, y1 := 0.35 - 0.3*u - 0.05*u^2]
dt[, y := y1*d + y0*(1 - d) + epsilon]

test_res <- ivmte(data = dt,
                  ivlike = y ~ d:factor(z),
                  propensity = d ~ factor(z),
                  m0 = ~u,
                  m1 = ~u,
                  target = "ate",
                  lpsolver = "gurobi")
```
```
Obtaining propensity scores...
Generating target moments...
    Integrating terms for control group...
    Integrating terms for treated group...
Generating IV-like moments...
 Error in ivEstimate(formula = sformula, data = sdata, components = scomponent,  : 
  The following components are not included in the IV-like specification: d:factor(z). Remove them from the components list, or update the corresponding IV-like specification. 
```
Since I didn't declare any components, `ivmte` creates a components list, which it pulls from the IV-like specification. So, I don't think it would make sense that `d:factor(z)` is not in the IV-like specification. (Maybe I am missing something here.)

**Comment by jkcshea** [comment]
I'm sorry for all these parsing issue with factors.
It looks like I made a mistake last month in commit 69a27972a606, when trying to address #119.
This should be addressed now.
