### ISSUE TITLE
Check type of data argument

### ISSUE THREAD

**Issue by johnnybonney** [jkcshea/ivmte#154]
This is just a suggestion that may (marginally) improve user-friendliness. You can definitely disregard it if you think it isn't worth the effort.

I often use the name `dt` for my data when I only have one `data.table` in the script. However, there have been a few times where I forgot to define `dt`. In those cases, if I call `ivmte` with `data = dt`, I get weird, ambiguous error messages --- this is because `dt` is the name of a function in the `stats` package. It takes me a little bit of time to recognize my error.

This is obviously 100% an error on the user's end, but I think adding a quick check that `dt` is of type `data.frame` would improve usability. [For one example of a possibility, I believe `lm` **a**) checks that `data` is a `data.frame` and **b**) if not **a**, tries to coerce `data` to a `data.frame` using `as.data.frame`.]

**Comment by a-torgovitsky** [comment]
That's a good idea -- should be easy to add too, right @jkcshea ?

My only concern is having compatibility with the few different data formats people use.
Since for example `data.frame` and `data.table` are different.
But perhaps the `data.table` package checks this? I am not sure how these aspects of R work.

**Comment by johnnybonney** [comment]
My understanding is that all these alternative data formats (commonly `data.table`, also `tibble` for the `tidyverse` crowd, etc.) are just sub-types of `data.frame` --- so checking if they are of `data.frame` type should still work. E.g.
```
> dt <- data.table(x = 0:1)
> class(dt)
[1] "data.table" "data.frame"
> is.data.frame(dt)
[1] TRUE
```
So I wouldn't expect compatibility issues.

**Comment by jkcshea** [comment]
Done!

Very straightforward to do.
As @johnnybonney said, `data.table` and `tibble` objects are also `data.frame`s.

Here's the errror message if non-data gets passed.
```
Error: 'data' argument must either be a data.frame, data.table, tibble, or matrix.
```
I think those are the main four classes of data...

**Comment by a-torgovitsky** [comment]
Perfect, thanks!

**Comment by johnnybonney** [comment]
Great!
