### ISSUE TITLE
Debug option to print out the MPS file

### ISSUE THREAD

**Issue by johnnybonney** [jkcshea/ivmte#158]
I have been recently attempting some specifications that imply very computational burdensome LP problems. Sometimes, this leads `ivmte` to run for hours on end with no visible progress while (I assume) Gurobi tries to tackle the LP problem. (I often end up terminating `ivmte` in these cases, since it doesn't seem to be getting anywhere.)

@a-torgovitsky pointed out that it might be nice to have a debug feature where the package can print out a prepared MPS file. That way, I can call the MPS file from the command line, allowing me to see what is going on under the hood with Gurobi (i.e. whether things are converging or not).

**Comment by jkcshea** [comment]
Done!

The debug mode was designed only for Gurobi.
So if you set `debug = TRUE` and you are using Gurobi, then two files will output: `lpMin.mps` and `lpMax.mps`.

These files are output before anything is solved.
So once those files pop up, you can terminate the R process.

Is that what you had in mind?

**Comment by johnnybonney** [comment]
Yes, this is exactly what I had in mind. Thanks!

**Comment by jkcshea** [comment]
I forgot about minimizing the criterion, which is another LP problem you may get stuck at.
So the code has now been updated to output that model as well (`lpCriterion.mps`).

**Comment by a-torgovitsky** [comment]
Cool, that seems like it was easy -- glad to know the R API for Gurobi has this functionality in it.

@johnnybonney you can run these with the gurobi_cl command which is buried in your gurobi installation (in mine it is ./linux64/bin/gurob_cl under the base Gurobi directory)
