### ISSUE TITLE
MTR specifications should(?) be equivalent but are not

### ISSUE THREAD

**Issue by johnnybonney** [jkcshea/ivmte#165]
Suppose we have a discrete covariate, `x`. I would expect the following specifications of `m1`/`m0` to be equivalent (so correct me if I am wrong here):
```
~factor(x) + factor(x):uSplines(...)
~factor(x) + uSplines(...) + factor(x):uSplines(...)
```
I would think that the first directly estimates x-specific u-splines, and the second estimates a u-spline for one x-group and estimates u-splines for the other x-groups relative to the first u-spline. (This is the logic from simple linear regression.)

However, that is not what I see. Here is an example:
```
library(data.table)
library(ivmte)

set.seed(1001)
N <- 2000

dt <- data.table(
  id = 1:N,
  u = runif(N),
  z = sample(1:4, N, replace = T),
  x = sample(1:6, N, replace = T),
  epsilon = rnorm(N, sd = .1)
)

dt[, p := (z == 1)*0.12 + (z == 2)*0.29 + (z == 3)*0.48 + (z == 4)*0.78]
dt[, d := as.integer(u <= p)]
dt[, y0 := 0.9 - 1.1*u + 0.3*u^2]
dt[, y1 := 0.35 - 0.3*u - 0.05*u^2]
dt[, y := y1*d + y0*(1 - d) + epsilon]

args <- list(
  data = dt,
  m0 = ~1, # for simplicity
  propensity = d ~ factor(z),
  ivlike = y ~ d + factor(z) + d:factor(z),
  target = "ate",
  lpsolver = "gurobi"
)

spline_knots <- seq(0, 1, length.out = 4)

# first -- factor(x) + factor(x):u-spline
args$m1 <- ~factor(x) +
  factor(x):uSplines(degree = 3, knots = spline_knots)
res1 <- do.call(ivmte, args)
# Bounds on the target parameter: [-0.08089865, 0.1434402]

# second -- factor(x) + u-spline + factor(x):u-spline
args$m1 <- ~factor(x) +
  uSplines(degree = 3, knots = spline_knots) +
  factor(x):uSplines(degree = 3, knots = spline_knots)
res2 <- do.call(ivmte, args)
# Bounds on the target parameter: [-0.06206086, 0.1361346]
```
The only difference between `m1` in the first and second specifications is the addition of a distinct `uSplines` term, which (if my initial logic was correct) should not change the results.

------------------------------

I did a little digging to see what the underlying cause might be, and I noticed the following differences in the maximizing LP parameters.
```
length(res1$lpresult$maxg1) # 54
length(res2$lpresult$maxg1) # 46
```
The second problem (adding the `uSplines` term) has 8 fewer LP parameters.
```
> setdiff(names(res1$lpresult$maxg1), names(res2$lpresult$maxg1))
[1] "u1S1.1:factor(x)1" "u1S1.2:factor(x)1" "u1S1.3:factor(x)1" "u1S1.4:factor(x)1" "u1S1.5:factor(x)1" "u1S1.6:factor(x)1" "u1S1.7:factor(x)1"
[8] "u1S1.8:factor(x)1"
```
If I am reading the output correctly, the addition of the separate `uSplines` term in `m1` somehow *removed* the interaction between a u-spline and the `x=1` group. That does not seem right to me.

**Comment by jkcshea** [comment]
Sorry about that, that was indeed a mistake.

I have code to deal with collinearities in the MTRs (although collinearities in the MTR shouldn't affect the bounds).
I essentially map each spline to a temporary variable, and then let R construct the design matrix using those temporary variables.
If R drops any of the temporary variables or their interactions, then I know I need to do the same with the corresponding spline.
The mistake I made was that I was dropping the case where the spline was not interacted with anything.

e.g. here's a simple example from your simulated data, where I use `z` as the temporary variable.
```R
> fit1 <- lm(y ~ factor(x) + factor(x):z, data = dt)
> fit2 <- lm(y ~ factor(x) + z + factor(x):z, data = dt)
> cbind(names(fit1$coef), names(fit2$coef))
      [,1]           [,2]          
 [1,] "(Intercept)"  "(Intercept)" 
 [2,] "factor(x)2"   "factor(x)2"  
 [3,] "factor(x)3"   "factor(x)3"  
 [4,] "factor(x)4"   "factor(x)4"  
 [5,] "factor(x)5"   "factor(x)5"  
 [6,] "factor(x)6"   "factor(x)6"  
 [7,] "factor(x)1:z" "z"           
 [8,] "factor(x)2:z" "factor(x)2:z"
 [9,] "factor(x)3:z" "factor(x)3:z"
[10,] "factor(x)4:z" "factor(x)4:z"
[11,] "factor(x)5:z" "factor(x)5:z"
[12,] "factor(x)6:z" "factor(x)6:z"
```
The second specification corresponds to the second column.
I was dropping the `z`, which would correspond to the spline not being interacted with anything.
That was why the number of terms decreased.

This should now be resolved!

**Comment by johnnybonney** [comment]
Perfect. The specifications now running as expected. Thanks!
