### ISSUE TITLE
Adding examples to the vignette

### ISSUE THREAD

**Issue by jkcshea** [jkcshea/ivmte#172]
Attached is a draft on how to plot the MTRs, as well as how to plot the average weights.
Let me know if you want anything changed.
(Didn't think it was wise to modify the actual vignette yet, so it's a separate file at the moment.)

[vignette-append.zip](https://github.com/jkcshea/ivmte/files/4366495/vignette-append.zip)

@a-torgovitsky I said I'd list all the objects returned so we can decide if we want any additional examples.
But there is actually a fairly large number of things returned, and not all of them are useful for analysis.
So I thought it would be better to summarize the kinds of numerical objects returned.
@johnnybonney  and @cblandhol are there examples that you think would have been helpful?

- The `x` and `u` points used to generate the audit grid are returned. 
Points that fail the audit are listed as well.
- The bounds/point estimates are returned.
- If bootstraps are performed, then the whole sequence of bounds/point estimates are returned, along with the confidence intervals and standard errors.
The confidence intervals and standard errors for every MTR coefficient is also returned.
- The target gamma moments and their weights are returned.
- The IV-like coefficient estimates, weights, and gamma moments are all returned.
- The propensity score model is returned.
- The LP problem for the bound is returned.
- If specification tests are performed during the bootstrap, then all the test statistics are returned.

Also, I thought some of the objects returned should be renamed.
These are the ones I think may affect @johnnybonney and @cblandhol (I'm sorry...).
- `sset` became `s.set`
- `lpresult` became `lp.result`
- `lpsolver` became `lp.solver`
- `splinesdict` became `splines.dict`
- `pvalue` became `p.value` (along with any of its derivatives, e.g. `specification.pvalue` became `specification.p.value`)
- `jtest` became `j.test` (along with any of its derivatives)

**Comment by johnnybonney** [comment]
> @johnnybonney and @cblandhol are there examples that you think would have been helpful?

I believe the three output elements we primarily use from `ivmte` are the bounds (which are straightforward), the weights on the IV-like moments, and the implied MTRs at the upper/lower bounds. So it seems to me (though I haven't looked at that new vignette) that you are including examples for all of these. Examples on the bootstrap and the differences between the different kinds of CIs (i.e. forward, backward) returned may also be useful (I haven't done inference in quite some time, so I'm not sure if this aspect of the package has changed).

> These are the ones I think may affect @johnnybonney and @cblandhol (I'm sorry...).

Thanks for the heads up!!

**Comment by a-torgovitsky** [comment]
Looks great!

Minor change is to more clear about uniqueness of the MTRs
- The returned MTR's are optimal, but not unique, unless there is point identification.
- The difference of `m1` and `m0` is the implied MTE curve, but is not really an estimate unless the MTRs are unique (point identification)

Otherwise, I think it's good to push these as added subsections to "Usage Demonstration"

**Comment by jkcshea** [comment]
> Minor change is to more clear about uniqueness of the MTRs

Done!

> Examples on the bootstrap and the differences between the different kinds of CIs (i.e. forward, backward) returned may also be useful 

Done! (kind of)

Seeing that the vignette includes provides references to Andrews and Han (2009) and the R paper, I thought it would be cleaner to simply show where the bootstraps are stored.
The user can then use those statistics to conduct inference in some other manner, should they choose to.
A little histogram is included in the vignette now.

**Comment by jkcshea** [comment]
> Minor change is to more clear about uniqueness of the MTRs

Just to be more clear, here's what I added.

"Taking the difference of the fitted values for `m1` and `m0` yields an MTE curve. However, unless there is point identification, the MTR and MTE curves are optimal but not unique. That is, the curves either maximize or minimize the treatment effect parameter, but there are other MTR and MTE curves that are observationally equivalent."

**Comment by a-torgovitsky** [comment]
Not just observationally equivalent, but also yield the same maximal or minimal value of the treatment effect parameter

**Comment by jkcshea** [comment]
Ah sorry, yes, I'll correct that.
