### ISSUE TITLE
Is it feasible/easy/a good idea to add S3 summary commands and suppress output completely?

### ISSUE THREAD

**Issue by a-torgovitsky** [jkcshea/ivmte#174]
I've been working with the package on a real project lately and I've started finding the output to be a bit annoying.

Even with `noisy = FALSE`, sometimes I just don't want to see information on the bounds and audit results printed.

It also seems like this is not the normal way to go about things in R.

I wonder if this might be a good idea:
1. Suppress the current output entirely.
2. Keep the print command the way it is. Maybe add some information on the specification used? Not sure if that's overkill.
2. Make `summary` show the full log of output that would be printed with `noisy = TRUE`

What do you think? It may require editing the vignette a bit too, but hopefully not much.

**Comment by jkcshea** [comment]
Sure, I think this is doable.
And yes, usually there is no output at all if the results are saved as an object.
I'll give this a shot.

**Comment by a-torgovitsky** [comment]
> And yes, usually there is no output at all if the results are saved as an object.

Is that true? I am not finding that. It still gives me the bounds and the audit summary.

**Comment by jkcshea** [comment]
Oh sorry, I should've quoted your post.
I meant that you were right and that usual R functions do not print anything if the results are saved to an object.
And as you point out, we're not doing that.

**Comment by a-torgovitsky** [comment]
Oh ok, got it. Thanks for clarifying

**Comment by jkcshea** [comment]
Just to clarify, complete suppression of all output should be implemented only when `noisy = FALSE` right?

So if `noisy = TRUE`, the user continues to see the output, with all the updates and such.

We could also change the default to be `noisy = FALSE`.

**Comment by a-torgovitsky** [comment]
Yeah, let's make this operate the same way `lm` does for example, with the default `noisy = FALSE`.
If I understand the way `lm` works, R will issue `print(lm)` if it is called interactively, and otherwise will be silent.

**Comment by jkcshea** [comment]
Sure thing, I'll do that.

**Comment by jkcshea** [comment]
Almost done!

Just want to double check on some changes.

> Keep the print command the way it is. Maybe add some information on the specification used? Not sure if that's overkill.

Something I added was the count of independent moments.
Maybe also the number of MTR coefficients, as a way to gauge how 'tight'/'loose' the LP problem is?

Will printing specifications like `m0` and `m1` be necessary if the user just ran the command? i.e. I'm assuming the user knows the specification used.
Or maybe you're looping through specifications? If so, I can include the specifications that are most likely to be looped over.

Also, all specifications are stored under `results$call.options`.
That way, if only the `results` object is available, the user can still figure out what model generated the results (but the data set is not saved).

> Make summary show the full log of output that would be printed with `noisy = TRUE`

This is no problem, but the output will be very long if there are many moments, or there are many bootstraps.
And showing things like
```
Obtaining propensity scores...

Generating target moments...
    Integrating terms for control group...
    Integrating terms for treated group...

Generating IV-like moments...
    Moment 1...
    Moment 2...
    Moment 3...
    Moment 4...
    Independent moments: 4 

Point estimate of the target parameter: -0.5740461

Bootstrap iteration 1...
    Point estimate:0.08374042

Bootstrap iteration 2...
    Point estimate:-0.8522671

Bootstrap iteration 3...
    Point estimate:-0.7677496
```
seems to be a bit much for a summary.

Nevertheless, all messages generated by `ivmte` are stored in `results$messages`, so the user will have access to them.

**Comment by a-torgovitsky** [comment]
> Something I added was the count of independent moments.
> Maybe also the number of MTR coefficients, as a way to gauge how 'tight'/'loose' the LP problem is?
> 
> Will printing specifications like `m0` and `m1` be necessary if the user just ran the command? i.e. I'm assuming the user knows the specification used.

The number of MTR coefficients is a good idea.
As well as the number of IV--like estimands (moments) _and_ the number that are independent.
If we have all this then I don't think the `m0` and `m1` specifications are necessary.

> This is no problem, but the output will be very long if there are many moments, or there are many bootstraps.
> And showing things like
> 
> ```
> Obtaining propensity scores...
> 
> Generating target moments...
>     Integrating terms for control group...
>     Integrating terms for treated group...
> 
> Generating IV-like moments...
>     Moment 1...
>     Moment 2...
>     Moment 3...
>     Moment 4...
>     Independent moments: 4 
> 
> Point estimate of the target parameter: -0.5740461
> 
> Bootstrap iteration 1...
>     Point estimate:0.08374042
> 
> Bootstrap iteration 2...
>     Point estimate:-0.8522671
> 
> Bootstrap iteration 3...
>     Point estimate:-0.7677496
> ```
> 
> seems to be a bit much for a summary.
> 
> Nevertheless, all messages generated by `ivmte` are stored in `results$messages`, so the user will have access to them.

Ok, yeah good point. No need to see the progress items, since you can only call `summary` after it's finished!

**Comment by jkcshea** [comment]
How does this look:

```R
> print(results)

Bounds on the target parameter: [-0.3777159, 0.3265236]
Audit terminated successfully after 1 round 
MTR coefficients: 3 
Independent/total moments: 4/4 
Minimum criterion: 0.07683692 
LP solver: Gurobi ('gurobi')

> summary(results)

Bounds on the target parameter: [-0.3777159, 0.3265236]
Audit terminated successfully after 1 round 
MTR coefficients: 3 
Independent/total moments: 4/4 
Minimum criterion: 0.07683692 
LP solver: Gurobi ('gurobi')

Bootstrapped confidence intervals (backward):
    90%: [-0.4596989, 0.4147051]
    95%: [-0.4820572, 0.4506745]
    99%: [-0.4892689, 0.4647329]
p-value: 0.92
Bootstrapped specification test p-value: 0.9
Number of bootstraps: 50
```

**Comment by a-torgovitsky** [comment]
Let's make `print` shorter, how about this:

```
Bounds on the target parameter: [-0.3777159, 0.3265236]
Audit terminated successfully after 1 round 
```

Also, a bit off-topic here, but is it possible to get both the forward and backward bootstrapped CI's without re-running the code? (i.e. are they both returned?)

**Comment by jkcshea** [comment]
Sure, I'll shorten print to look like that.

And yes, both forward and backward bootstrapped CIs are returned under `results$bounds.ci`.
I think we just decided to show one of them in the summary so it wasn't too cluttered.

**Comment by a-torgovitsky** [comment]
Ok got it. This all sounds good, thanks!
