### ISSUE TITLE
Strange infeasibility issue/message

### ISSUE THREAD

**Issue by jkcshea** [jkcshea/ivmte#178]
The example from #177 becomes infeasible after a sufficient number of audits.
Why is this?

Also, in the infeasibility error message, why is there a `NULL`?

```R
Error: No feasible solution to the criterion minimization problem.
This should only happen if the implied parameter space is empty. 
The likely cause of an empty parameter space is incoherent 
shape restrictions. For example, m1.lb = 0, m1.ub = 1, NULL 
are all set simultaneously. Try changing the shape constraints 
on the MTR functions. 
```

**Comment by jkcshea** [comment]
I've resolved the `NULL` issue.
For the sake of documentation:
This problem occurred because the function did not update the index of shape constraints in the initial grid throughout the audit procedure.
If the problem is infeasible, the function uses these indexes to suggest to the user which constraints may be responsible for the infeasibility error.
Since the the indexes weren't updated, the function could not determine the type of one of the constraints potentially causing infeasibility, thus returned a `NULL`.

The error occurs because of improper scaling in the data.
Rescaling the data resolves the issue.
A new error message has been included to warn users of improper scaling in the data.

**Comment by a-torgovitsky** [comment]
Thanks, could you give some more detail on what you mean by improper scaling?
I am interested in what it is someone could input that would mess things up.

**Comment by jkcshea** [comment]
Oh, I forgot to include my note to #177!

For the sake of documentation:
The cube of a covariate in the order of `1e6` was included as a covariate.
The magnitude of this is `1e18`.
Accounting for the scale of other data, the range of magnitude exceeds double precision.
Gurobi's solver would return a `NUMERIC` status, meaning that "Optimization was terminated due to unrecoverable numerical difficulties."

**Comment by a-torgovitsky** [comment]
Got it, thanks.

Good catch, certainly not much we can do about something like that!
Presumably the OLS results were also garbage as well.

Can you put a check in for `NUMERIC` as a return?
Before what were was being checked for?
Just `SOLVED` or `SOLVED?`? Any other categories?

**Comment by jkcshea** [comment]
> Can you put a check in for NUMERIC as a return?

Done!

> Before what were was being checked for?
Just SOLVED or SOLVED?? Any other categories?

Yes, I'm embarrassed to say it was only checking for that.
I can't think of a reason why I did not include a check for all statuses other than being lazy/negligent.
I plan to include checks for the following (for Gurobi):
- OPTIMAL
- INFEASIBLE
- INF_OR_UNBD
- UNBOUNDED
- NUMERIC-SUBOPTIMAL

The full list is here:
https://www.gurobi.com/documentation/9.0/refman/optimization_status_codes.html

I can do the same for CPLEX and lpSolve.

**Comment by a-torgovitsky** [comment]
I don't think there's a need to be exhaustive.
But if there's a return code that we know is potentially associated with a specific problem (such as this one), then it would be good to give the user an informative error message so that they have some idea of what to look at. This one of scaling I expect would be a common issue.

Return codes that we have never seen or can't anticipate could just be returned with the specific code and a suggestion that the user report the problem by posting an issue here.

**Comment by a-torgovitsky** [comment]
By the way, I had thought that we dealt with this scaling issue before and that there was some check already implemented for poorly-scaled models. Is that right? Did the check not get triggered here?

**Comment by jkcshea** [comment]
You're right, we did do a bunch of stuff with the scaling.
After much searching, I found the [relevant post](https://github.com/jkcshea/ivmte/issues/161#issuecomment-566806467) on why we no longer have this check.
In summary, we didn't like having warning messages when Gurobi is able to solve the problem, and decided to let the debug mode inform the user of all the details of optimization.
Thus, we got rid of the warning.

Should we bring it back? Or is the new error code sufficient?

**Comment by a-torgovitsky** [comment]
Ok I remember this now. I think it was the right decision. We don't want a hard threshold of when we think that there _might_ be numerical issues, because often there won't be it.

However, in this case Gurobi returns an error due to the poor scaling.
So, that combined with the knowledge that the model is poorly scaled should be something that the user should be informed about.
