### ISSUE TITLE
glm bug

### ISSUE THREAD

**Issue by slacouture** [jkcshea/ivmte#182]
Hi!

When using the package on a very simple estimation, I am finding a weird `glm` warning message that is, in turn, potentially making `ivmte` spit out an unintuitive output. 

I am specifying a simple propensity model separable in covariates `` p.form <- as.formula("D ~ Z1 + Z2 + female + age + admin_yos")`` and the following specs for the program
```
args <- list(data = data, 
             ivlike =  as.formula("Y ~  Z1 + Z2 + female + age + admin_yos"),
             subset = l(D == 1),
             target = "genlate",
             genlate.lb = 0,
             genlate.ub = .75,
             m0 = ~ 1,
             m1 = ~ uSplines(degree = 3, knots = seq(0.2,0.75,length.out = 5)), 
             propensity = p.form,
             m0.lb = 0, 
             m0.ub = 0,
             m1.lb = 0, 
             m1.ub = 1) 
```
What is odd is that I get a warning message ``glm.fit: algorithm did not converge`` and that the estimated target parameter is not a point but bounds, which shouldn't be the case
```
do.call(ivmte, args) 
Bounds on the target parameter: [0.6072055, 0.9219987]
Audit terminated successfully after 2 rounds
```
This is true regardless of using a ``logit`` or ``probit`` model. However, you can try this specification of the propensity score using glm without any problem
```
Call:  glm(formula = p.form, family = binomial(link = "probit"), data = data)

Coefficients:
(Intercept)           Z1           Z2       female          age    admin_yos  
  -1.227400     0.042488     0.139158     0.190301    -0.001393     0.086529  

Degrees of Freedom: 9321 Total (i.e. Null);  9316 Residual
Null Deviance:	    12900 
Residual Deviance: 12130 	AIC: 12140
```

Furthermore, if you estimate the p-score separately and tell the program to use such estimate and point out the treatment variable, you get the expected point identified target parameter
```
data[, c("p")] <- predict(glm(p.form, family = binomial(link = "probit"), 
                               data = data), data, type = "response")
args[["data"]] <- data
args[["propensity"]] <- "p"
args[["treat"]] <- "D"
do.call(ivmte, args)
Bounds on the target parameter: [0.5344653, 0.5344653]
Audit terminated successfully after 2 rounds
```
You can find the replication files for this error [here](https://github.com/jkcshea/ivmte/files/5087224/glm_bug.zip). 

Thank you!

**Comment by a-torgovitsky** [comment]
My guess is that this is due to
```
subset = l(D == 1)
```

This is going to get passed along to the `glm` call with `ivmte`.
Then you are trying to do a probit/logit with an outcome variable that doesn't vary at all.

**Comment by a-torgovitsky** [comment]
@jkcshea assuming that is true, the concerning part is that `ivmte` continues to run and spit out bounds. What is happening here?

**Comment by slacouture** [comment]
Well, now that you mention it, the use of `subset` here is kind of redundant: if I drop it I get the same error and the same estimates (also when I use the estimated p-score). Anyways, I thought the `subset` option was a condition only for the `ivlike` argument (that is what I understood from the documentation), thank you for the clarification about this!

**Comment by a-torgovitsky** [comment]
Yes you're right, I was forgetting what `subset` referred to!
@jkcshea I think this needs to be looked into.

**Comment by a-torgovitsky** [comment]
Thanks @jkcshea , this makes perfect sense.
Perhaps we should also have a warning whenever there are incomplete cases that get dropped?
e.g. what would happen if `age` were missing for an observation? Would it be silently dropped from the entire procedure?

@slacouture the solution here is indeed to set `Y = 0` for `D = 0` instead of `NA`.

**Comment by slacouture** [comment]
Thank you @jkcshea, I didn't know the package used complete observations for all the estimations, as I saw them as separate steps so I thought it would work this way. Using `YD` works perfectly.

**Comment by jkcshea** [comment]
> Perhaps we should also have a warning whenever there are incomplete cases that get dropped?
e.g. what would happen if age were missing for an observation? Would it be silently dropped from the entire procedure?

Ah that's right, we do silently drop any observation that is missing any _relevant_ variable.

The way the subsample of completed observations is as follows:
1. Determine all the variables used in the IV-like specifications, MTRs, propensity score formula, subsets, LATE arguments, etc. 
2. Then restrict the data to the observations that are complete with respect to those variables.

So every component in the estimation procedure (propensity score model, IV-like moments, etc.) are all based on the same data set.
I recall agreeing on this approach sometime long ago, and it is the same approach taken by other packages (e.g. `ivreg` does the same).

How detailed do we want the warning message when dropping incomplete observations?
Maybe something simple like,
```R
Warning: 2 incomplete observations dropped.
```

**Comment by a-torgovitsky** [comment]
Simple warning looks good.

Otherwise I think the procedure we agreed upon is still fine.
It's a little less transparent I suppose just because there are more moving parts in `ivmte` than in `ivreg`.
But having the warning in there should solve things.

**Comment by jkcshea** [comment]
Done!
