### ISSUE TITLE
How do ATT/ATE/etc. deal with covariates?

### ISSUE THREAD

**Issue by a-torgovitsky** [jkcshea/ivmte#183]
I know we must have discussed this in the past, but I couldn't figure it out from looking at our documentation, then I became confused/concerned when looking at the code.

Suppose I have
```r
m0 = ~ u + x
m1 = ~ u + x
target = "ate"
```
Let's say I estimate this with `point = TRUE`.
Then we have 
```tex
m_{0}(u,x) = \alpha_{0}u + \beta_{0}x
m_{1}(u,x) = \alpha_{1}u + \beta_{1}x
```

How is the target parameter computed? Is it

a) `(\alpha_{1} - \alpha_{0})E[U] + (\beta_{1} - \beta_{0})E[X]` with `E[U]` replaced by .5, and `E[X]` replaced by the sample mean of `X`?

or is it 
b) `(\alpha_{1} - \alpha_{0})E[U}`

?
(I am hoping it is a!!)

**Comment by jkcshea** [comment]
I apologize for not having responded to this sooner.
I am happy to tell you it is indeed (a).

Below are the lines where we call GMM.

https://github.com/jkcshea/ivmte/blob/8133f9955bc559d9df4d98824c169f30c5b0fa1e/R/mst.R#L2976-L2980

The first argument `sset` contains all the moments for the IV-like estimands.
The code uses these moments to estimate the MTR coefficients via GMM.

The next two arguments `gstar0` and `gstar1` contain the target moments for treated and untreated agents.
So these arguments are your `E[U]` and `E[X]` terms in your example.
These target moments are combined with the GMM coefficient estimates to obtain the target parameter.

**Comment by a-torgovitsky** [comment]
Ok thanks.
My question was really about how the target moments are generated.
Let's index the ATE by x --- for example in the specification above $m_{1} - m_{0}$ would be a function of x.

If we use `target = ate` then the default is to take the average of ATE(X) over X with respect the sample distribution.
Is that right?

**Comment by jkcshea** [comment]
Yes, that's right.
And for the other target parameters, the averaging is done with the appropriate weights.
