### ISSUE TITLE
Sign up for a DOI

### ISSUE THREAD

**Issue by a-torgovitsky** [jkcshea/ivmte#190]
I believe the package maintainer has to do this.
It looks very easy, here's a guide:
https://guides.github.com/activities/citable-code/

**Comment by jkcshea** [comment]
Indeed very straightforward, but we need to have a 'Release' before getting a DOI.
So I'll try to clear up these issues, and then we can have a clean release.

**Comment by a-torgovitsky** [comment]
Ok, sounds good. None of these are really fatal issues. The package is being used effectively for the most part.

**Comment by jkcshea** [comment]
Done!

We have a DOI now: 10.5281/zenodo.4050609

**Comment by a-torgovitsky** [comment]
Nice, can we get the badge on the README.md?

**Comment by jkcshea** [comment]
Done! 
The position of the badge is as high up as I can get it.
