### ISSUE TITLE
Bootstrapping the direct MTR regression

### ISSUE THREAD

**Issue by jkcshea** [jkcshea/ivmte#195]
The target parameter may or may not be point identified in each bootstrap sample.
Since the estimation procedure for the point-identified case is different from the partially identified case, I reason that we cannot treat the point ID estimate as a bound that has collapsed to a single point.
If that's right, then what's a good way to bootstrap?

In the original estimation procedure, the S-set could change across bootstraps due to collinearity.
We dealt with this by redrawing the bootstrap sample until the S-set was the same as that of the original sample, and then reporting the number of times this occurred.
Maybe we take a similar approach?
i.e., if the original sample satisfies point identification, we only use the bootstrap samples that also satisfy point identification?
And likewise for the partially identified case?

**Comment by a-torgovitsky** [comment]
>  i.e., if the original sample satisfies point identification, we only use the bootstrap samples that also satisfy point identification?

Yes that's good. Having collinearity in the bootstrap draws should happen "with small probability" so I think we are justified with skipping them and redrawing.

>  And likewise for the partially identified case?

For the partially identified case, I think the best thing is to always use the partial identification procedure in the resamples, even if it appears as if they are point identified. Again, this should happen "with small probability," so it's probably not going to be a big issue.

**Comment by jkcshea** [comment]
Okay, the function now allows the user to bootstrap when using the direct MTR regression.
