### ISSUE TITLE
Change 'lpsolver' to 'solver'

### ISSUE THREAD

**Issue by jkcshea** [jkcshea/ivmte#197]
Since we're no longer only using Gurobi and CPLEX for LP problems, it seems confusing to have all these `lpsolver` arguments.
So those will be changed to just `solver`, or `solver.options`.

This affects the options:
*`lpsolver`
*`lpsolver.options`
*`lpsolver.presolve`
*`lpsolver.options.criterion`
*`lpsolver.options.bounds`

Apologies to @johnnybonney @cblandhol for the inconvenience caused.

**Comment by a-torgovitsky** [comment]
Maybe for "backwards compatibility" it is better to just introduce new options while keeping the `lpsolver` ones? Then alias the `lpsolver` ones to `solver` and issue a warning to the user that the option is deprecated?

Also, probably some of the error/warning messages need to be adjusted to reflect the same issue.

**Comment by jkcshea** [comment]
> Maybe for "backwards compatibility" it is better to just introduce new options while keeping the lpsolver ones? Then alias the lpsolver ones to solver and issue a warning to the user that the option is deprecated?

Done!

And we have a lot of error and warning messages, as well as documentation.
So I'll be working on those.
