### ISSUE TITLE
Uninformative error message when using splines in direct MTR regression

### ISSUE THREAD

**Issue by cblandhol** [jkcshea/ivmte#205]
The direct MTR regression throws an uninformative error when using splines in the basis functions. If I understand it correctly this is because direct MTR regression does not work with splines as bases functions because we cannot express the constraints in terms of equation (6) in the documentation posted in issue #194. 

It would be helpful if the error message was more informative. Here is an example that illustrates the behavior and the error message:

```r
library(ivmte) 
library(data.table)

# simulate data
set.seed(1)
n <- 5000
u <- runif(n)
z <- as.numeric(rbinom(n,1, .5))
d <- as.numeric(u < z*.25)

v0 <- rnorm(n) + .2*u
m0 <- 0
y0 <- as.numeric(m0 + v0 > 0)

v1 <- rnorm(n) - .2*u
m1 <- .5
y1 <- as.numeric(m1 + v1 > 0)

y <- d*y1 + (1-d)*y0
ivmteSimData <- data.frame(y,d,z)

args <- list(data = ivmteSimData,
             target = "att",
             m0 = ~ uSplines(degree = 0, knots = c(0.25, 0.5)) ,
             m1 = ~  uSplines(degree = 0, knots = c(0.25, 0.5)) ,
             propensity = d ~ factor(z))

# using ivlike
args$ivlike <- c(y ~ factor(d)*factor(z))

do.call(ivmte, args)


```

```r
Bounds on the target parameter: [0.1176324, 0.1324768]
Audit terminated successfully after 1 round

```

```r
# bounds using direct MTR regression
args$ivlike       <- NULL
args$outcome <- "y"

do.call(ivmte, args)

```

```r
LP solver: Gurobi ('gurobi')

Obtaining propensity scores...

Generating target moments...
    Integrating terms for control group...
    Integrating terms for treated group...

Performing direct MTR regression...
Error in lm.fit(x = resX, y = drY) : NA/NaN/Inf in 'x'

```

**Comment by a-torgovitsky** [comment]
I'm not sure if this is true:
> If I understand it correctly this is because direct MTR regression does not work with splines as bases functions because we cannot express the constraints in terms of equation (6) in the documentation posted in issue #194.

If it is, I can't remember the rationale.
There isn't anything inherently more difficult about constraining splines than constraining other functions (splines are at the end of the day just piecewise polynomials).
So I think this is a bug.

**Comment by jkcshea** [comment]
Hm, this is indeed an error.
The direct MTR regression is supposed to support splines, I remember having an exchange with @slacouture about this...
I will take care of this!

**Comment by jkcshea** [comment]
This is resolved now.

When testing the rescaling methods, I did not consider cases where variables were 0 for all observations.
But in the example above, some of the spline components are 0 for all observations.
These variables therefore have a norm of 0.
But when rescaling the data, we divide each variable by its norm---so we were dividing by zeroes.
That was why R was reporting `Error in lm.fit(x = resX, y = drY) : NA/NaN/Inf in 'x'`
So to resolve this issue, variables with norm 0 are assigned a norm of 1.

@cblandhol let me know if this works for you, too.

**Comment by a-torgovitsky** [comment]
Makes perfect sense, and I guess this must have been happening before `lm` goes through and drops collinear variables.
Thanks @jkcshea !
