### ISSUE TITLE
Erroneous warning message for ignoring shape constraints

### ISSUE THREAD

**Issue by a-torgovitsky** [jkcshea/ivmte#213]
```r
ivmte(
  data = AE,
  ivlike = c(worked ~ morekids + samesex + morekids * samesex),
  target = "ate",
  m0 = ~ u,
  m1 = ~ u,
  propensity = morekids ~ samesex,
  solver = "gurobi"
)

Point estimate of the target parameter: -0.07791036

Warning message:
MTR is point identified via GMM. Shape constraints are ignored.
```

There aren't any shape constraints here, so nothing to ignore.

**Comment by a-torgovitsky** [comment]
Yes you're right, although I still worry that this will confuse people.
I would be ok with this warning message if the input had explicitly specified `m0.lb` for example.
But given that the user didn't put that in, and may just want to be estimating point identified models, it seems like it could create confusion.
Is it easy to detect whether there was any input received for the shape constraint options?
I guess we would only want to print this message if the user passed any shape constraint input.

**Comment by jkcshea** [comment]
> Is it easy to detect whether there was any input received for the shape constraint options?

Yes! I will do that.
