### ISSUE TITLE
Unnecessary warning message about custom audit grids

### ISSUE THREAD

**Issue by johnnybonney** [jkcshea/ivmte#231]
Whenever I specify a custom audit grid, I get the following warning:
```
Argument 'initgrid.nu' is ignored when a custom initial grid 'initgrid.u' is passed.
```
But I haven't specified `initgrid.nu`---only `initgrid.u`. (I imagine the warning is catching the default value of `initgrid.nu`, which indeed should be ignored, but probably no reason to warn the user about that.)

**Comment by jkcshea** [comment]
Resolved!

> I imagine the warning is catching the default value of `initgrid.nu`

That's exactly what was happening!
