### ISSUE TITLE
Error when error with bounds

### ISSUE THREAD

**Issue by johnnybonney** [jkcshea/ivmte#232]
When estimating with the "hard" constraints approach, and there is an underlying error with obtaining the bounds, I get output/error like this:
```
Performing audit procedure...
    Solver: Gurobi ('gurobi')
    Criterion constraint: Hard, l1 norm 
    Generating initial constraint grid...

    Audit count: 1
    Minimum criterion: 1.939618e-06
    Obtaining bounds...
Error in audit(vars_data = vars_data, initgrid.x = list(village_id = c(1L,  : 
  object 'minoobseq' not found
```

This seems to be due to a typo (it's the only time `minoobseq` appears, as opposed to `minobseq`), which occurs here:
https://github.com/jkcshea/ivmte/blob/31a7427a591206f83bd76fad542934d5fd491d63/R/audit.R#L1068

(This is such a small issue that I would fix it myself, but I'm not super experienced with collaborating on git and don't want to cause more problems than I would be solving!)

**Comment by jkcshea** [comment]
No problem, it's fixed!
