### ISSUE TITLE
Can we check for point identification before checking for LP/QP packages?

### ISSUE THREAD

**Issue by a-torgovitsky** [jkcshea/ivmte#233]
Example:

```r
library("ivmte")

ivmte(data = AE,
      outcome ~ worked,
      propensity = morekids ~ samesex,
      target = "att",
      m0 = ~ u,
      m1 = ~ u)
```

If Gurobi is installed, this works fine.
But Gurobi is not needed for this, since it's point identified.
If Gurobi is not installed, I get this error:
```r
Error: A direct regression via quadratic programming may only be peformed if the solver is Gurobi or MOSEK. Please install either solver and set 'solver = "gurobi"' or 'solver = "rmosek"'.
```

I think we want people to be able to use `ivmte` for point identified cases without having to have a solver installed.

**Comment by jkcshea** [comment]
Ah sorry, I thought I had taken care of this in the past.
I must have undone it or misremembered.
It should now be fixed!
