### ISSUE TITLE
Encountering an error in the section of estimate bounds on the ATE

### ISSUE THREAD

**Issue by 19seh99** [jkcshea/ivmte#235]
When running the codes of the section estimate bounds on the ATE, I encountered the error as follows:

> library("ivmte")
results <- ivmte(data = AE,
                 target = "att",
                 m0 = ~ u + yob,
                 m1 = ~ u + yob,
                 ivlike = worked ~ morekids + samesex + morekids*samesex,
                 propensity = morekids ~ samesex + yob,
                 noisy = TRUE)
#> Error: GMM system is underidentified: there are 6 unknown MTR coefficients and 4 moment conditions defined by 
#> IV-like  specifications. Either expand the number of moments, or adjust m0 and m1.
#> In addition: Warning message:
#> None of the compatible solvers are installed, so estimation is only possible under point identification. MTR coefficients 
#> will be estimated using GMM, and an estimate of the target parameter will be returned only if the MTR coefficients are 
#> point identified.

**Comment by a-torgovitsky** [comment]
I am getting the output indicated in the readme.

I think you need to install a linear programming package in step 2 here:
https://github.com/jkcshea/ivmte#installation-and-requirements

**Comment by 19seh99** [comment]
Hello;
I have installed it completely, but I still get the same error.

‫‪Alexander Torgovitsky‬‏ ***@***.***‬‏> در تاریخ چهارشنبه
۱۵ نوامبر ۲۰۲۳ ساعت ۵:۴۱ نوشت:‬

**Comment by a-torgovitsky** [comment]
which LP package did you install?

**Comment by jkcshea** [comment]
Good news: you only need one of those packages.
I recommend you install Gurobi.
It will allow you to use more features of the package.

**Comment by 19seh99** [comment]
Thank you for your attention. However, I encountered another error when
running the following code :

> args[["m1"]] <- ~ u + factor(yob)55 + factor(yob)60Error: unexpected numeric constant in "args[["m1"]] <- ~ u + factor(yob)55"


‫‪jkcshea‬‏ ***@***.***‬‏> در تاریخ جمعه ۱۷ نوامبر ۲۰۲۳ ساعت
۱۸:۳۹ نوشت:‬

**Comment by jkcshea** [comment]
It looks like you're running the example code from our vignette.
That's great, thanks!

Unfortunately, R can't parse `factor(yob)55`
(although that's how R names dummy variables in regressions).
The work around is to declare the dummy as `(yob == 55)`.

E.g.,  `args[["m1"]] <- ~ u + (yob == 55) + (yob == 60)`

Check out the vignette for more examples of how to declare MTRs.

**Comment by 19seh99** [comment]
Yes, I am researching the instrumental variable topic, and your joint paper
with Mr. Torgovitsky caught my interest. Currently, whenever I invoke the
loopivmte function, I encounter an error, for example:

>   ### Function for computing genlate bounds at different values ###> loopivmte <- function(args, alphalist) {+   df.lb <- data.frame(alpha = alphalist, value = NA, type = "lb")+   df.ub <- data.frame(alpha = alphalist, value = NA, type = "ub")+   for (i in 1:length(alphalist)) {+     args[["genlate.lb"]] <- max(p[1] - alphalist[i], 0)+     args[["genlate.ub"]] <- min(p[2] + alphalist[i], 1)+     r <- do.call(ivmte, args)+     df.lb$value[i] <- r$bound[1]+     df.ub$value[i] <- r$bound[2]+   }+   return(rbind(df.lb, df.ub))+ }>   ### Run the quadratic case ###> plotquadratic <- loopivmte(args, alphalist)Error in args[["genlate.lb"]] <- max(p[1] - alphalist[i], 0) :
  object of type 'closure' is not subsettable


‫‪jkcshea‬‏ ***@***.***‬‏> در تاریخ شنبه ۱۸ نوامبر ۲۰۲۳ ساعت
۱:۴۶ نوشت:‬

**Comment by 19seh99** [comment]
sorry i Excuse me, but the error in the previous message was a mistake.
Here is the correct error message:

Error: 'genlate.lb' must be strictly less than 'genlate.ub'.



‫‪Seyyed Ehsan Hoseinzadeh‬‏ ***@***.***‬‏> در تاریخ شنبه ۱۸ نوامبر
۲۰۲۳ ساعت ۱۵:۳۵ نوشت:‬

**Comment by jkcshea** [comment]
It looks like this is what you are trying to run:
```R
loopivmte <- function(args, alphalist) {
    df.lb <- data.frame(alpha = alphalist, value = NA, type = "lb")
    df.ub <- data.frame(alpha = alphalist, value = NA, type = "ub")
    for (i in 1:length(alphalist)) {
        args[["genlate.lb"]] <- max(p[1] - alphalist[i], 0)
        args[["genlate.ub"]] <- min(p[2] + alphalist[i], 1)
        r <- do.call(ivmte, args)
        df.lb$value[i] <- r$bound[1]
        df.ub$value[i] <- r$bound[2]
    }
    return(rbind(df.lb, df.ub))
}
### Run the quadratic case
plotquadratic <- loopivmte(args, alphalist)
```

But then you get the following error:
```R
Error: 'genlate.lb' must be strictly less than 'genlate.ub'.
```

The arguments `genlate.lb` and `genlate.ub` determine the region of integration
(`lb` stands for "lower bound," `ub` stands for "upper bound").
The `ivmte` function is going to integrate the MTRs from `genlate.lb` up to `genlate.ub`.
So you must set `genlate.lb` to be strictly less than `genlate.ub`.
The error is telling you that you did not do this.

The error likely stems from these two lines of code, whrere you set `genlate.lb` and `genlate.ub`.
```R
        args[["genlate.lb"]] <- max(p[1] - alphalist[i], 0)
        args[["genlate.ub"]] <- min(p[2] + alphalist[i], 1)
```
So take a look there and see what values you actually assigned.

**Comment by 19seh99** [comment]
Thank you very much for your help. Now, in your opinion, what is the reason
for this error?
[image: image.png]

‫‪jkcshea‬‏ ***@***.***‬‏> در تاریخ یکشنبه ۱۹ نوامبر ۲۰۲۳
ساعت ۱:۲۲ نوشت:‬

**Comment by jkcshea** [comment]
I'm afraid your picture wasn't properly attached.
It looks like you're responding via email.
Maybe you can successfully attach the photo by responding on GitHub.
