### ISSUE TITLE
Error encountered in the loopivmte function

### ISSUE THREAD

**Issue by 19seh99** [jkcshea/ivmte#236]
While running the following codes, after run the loopivmte function, I encountered an error containing: The object "late.Z" was not found. As follows:

![Screenshot 2023-11-28 131702](https://github.com/jkcshea/ivmte/assets/64384903/a023f7f4-caf2-4b3a-972b-1f7ce963d996)

**Comment by jkcshea** [comment]
Hi @19seh99,

I'm so sorry for the slow response this time.
I think you've spotted a bug.
I will try to take care of it this week.
I apologize again for the delay.

Josh

**Comment by 19seh99** [comment]
No problem, take your time.

**Comment by jkcshea** [comment]
Hi @19seh99,
I'm terribly sorry for not returning to this issue earlier.
The issue has been resolved.
Let me know if you have any questions.
